# Generated by Django 5.1 on 2024-09-06 05:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_product_end_date_product_picture_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 5, 15, 24, 263208, tzinfo=datetime.timezone.utc)),
        ),
    ]
