# Generated by Django 5.1 on 2024-09-06 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_product_alter_product_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 7, 14, 54, 255873, tzinfo=datetime.timezone.utc)),
        ),
    ]
